# Generated by Django 5.2.7 on 2025-11-04 12:36

from django.db import migrations, models


def populate_worksite_country_names(apps, schema_editor):
    Worksite = apps.get_model("worksites", "Worksite")
    from config.countries import country_name_for

    for worksite in Worksite.objects.all():
        worksite.country_name = country_name_for(worksite.country_code)
        worksite.save(update_fields=["country_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksite',
            name='country_code',
            field=models.CharField(choices=[('PL', 'Polska'), ('SK', 'Slowacja'), ('CZ', 'Czechy'), ('DE', 'Niemcy'), ('AT', 'Austria'), ('HU', 'Wegry'), ('LT', 'Litwa'), ('LV', 'Lotwa'), ('EE', 'Estonia'), ('UA', 'Ukraina'), ('RO', 'Rumunia'), ('BG', 'Bulgaria'), ('HR', 'Chorwacja'), ('SI', 'Slowenia'), ('SE', 'Szwecja')], default='PL', max_length=3),
        ),
        migrations.AddField(
            model_name='worksite',
            name='country_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.RunPython(populate_worksite_country_names, migrations.RunPython.noop),
    ]
