# Generated by Django 5.2.7 on 2025-11-04 09:35

import django.db.models.deletion
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('labsites', '0001_initial'),
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='active_laboratory',
            field=models.ForeignKey(blank=True, help_text='Ostatnio wybrane aktywne laboratorium kierownika.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_managers', to='labsites.labsite'),
        ),
    ]
