# Generated by Django 5.2.7 on 2025-11-10 10:46

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_user_active_laboratory'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(choices=[('PL', 'Polska'), ('SK', 'Slowacja'), ('CZ', 'Czechy'), ('DE', 'Niemcy'), ('AT', 'Austria'), ('HU', 'Wegry'), ('LT', 'Litwa'), ('LV', 'Lotwa'), ('EE', 'Estonia'), ('UA', 'Ukraina'), ('RO', 'Rumunia'), ('BG', 'Bulgaria'), ('HR', 'Chorwacja'), ('SI', 'Slowenia'), ('SE', 'Szwecja')], default='PL', help_text='Kraj pochodzenia lub pracy uzytkownika.', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='country_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
